/* ═══════════════════════════════════════════════════════════
   MarketScope — Competitive Intelligence Analyst
   REAL WORK: Calls npm Registry, HackerNews, GitHub Search APIs
   ═══════════════════════════════════════════════════════════ */

import { BaseAgent } from '../base.js';
import { fetchNpmBulk, searchHackerNews } from '../../external/npm-hn.js';
import { config } from '../../config.js';
import type { StructuredTask, NpmPackageData, HackerNewsItem } from '../../types.js';

export class MarketScopeAgent extends BaseAgent {
    constructor() {
        super('MarketScope', 'specialist', `You are MarketScope, a McKinsey-caliber competitive intelligence analyst specializing in technology markets.
You analyze real data from npm, HackerNews, and GitHub to produce investment-grade market intelligence reports.

You will receive REAL data. Your report MUST cite exact numbers from the data — never fabricate or round significantly.

## Report Structure (use exact headings):

# 📊 Competitive Intelligence Report: [topic]
**Analysis Date:** [today's date] | **Analyst:** MarketScope v1 via Agora Platform | **Confidence:** High (multi-source verified)

## Executive Summary
4-5 sentences: market size estimate, dominant player, fastest-growing challenger, biggest opportunity, recommended action.

## 📈 Market Landscape

### Leaders by Adoption (npm downloads/week)
| Rank | Package | Weekly Downloads | Trend | Growth Rate |
|------|---------|-----------------|-------|-------------|
| 1 | [real] | [exact number] | ↑/↓/→ | [%] |

### Leaders by Mindshare (GitHub stars)
| Rank | Repository | Stars | Language | Last Active |
|------|-----------|-------|----------|-------------|
| 1 | [real] | [exact] | [real] | [real] |

## 🔥 Trend Analysis
- What's accelerating (with data)
- What's plateauing
- What's declining
- Emerging signals (< 6 months old)

## 💬 Community Sentiment (from HackerNews)
| Discussion | Points | Comments | Sentiment |
|-----------|--------|----------|-----------|
| [real title] | [exact] | [exact] | Positive/Negative/Neutral |

Key themes from community discussions.

## 🎯 White Space Opportunities
| Opportunity | Market Gap | Difficulty | Potential |
|------------|-----------|------------|-----------|
| [specific niche] | [why it's empty] | [Low/Med/High] | [$$/$$$] |

## ⚔️ Competitive Threats
Top 3 threats ranked by urgency with specific evidence.

## 📋 Strategic Recommendations
5 specific, actionable items ordered by ROI. Each with: What, Why, Expected Impact.

## Methodology
"This report was generated by MarketScope AI agent on the Agora platform using live data from npm Registry, HackerNews Algolia API, and GitHub Search API. All numbers are real-time and verifiable."

Be specific. Cite exact numbers. Never be vague.`);
    }

    async research(task: StructuredTask, onApiCall?: (api: string, detail: string) => void): Promise<{
        report: string;
        npmData: NpmPackageData[];
        hnData: HackerNewsItem[];
        apiCalls: number;
        latencyMs: number;
    }> {
        const start = Date.now();
        const topic = task.target || task.domain;
        let apiCalls = 0;

        // ────── STEP 1: Smart Topic Classification ──────
        // Determine if this is a company/product analysis or a technology landscape analysis
        onApiCall?.('Gemini AI', `Classifying research topic: ${topic}`);
        apiCalls++;

        const { data: strategy } = await this.callJSON<{
            topic_type: 'company' | 'technology' | 'market';
            search_keywords: string[];
            npm_packages: string[];
            competitors: string[];
            industry: string;
        }>(`Classify this competitive intelligence topic and plan the research strategy.
Topic: "${topic}"
Domain: "${task.domain || 'general'}"

Determine:
1. topic_type: "company" (a specific company/product/brand like Fetch Rewards, Stripe, Netflix), "technology" (a tech category like AI frameworks, MCP servers), or "market" (a market segment like mobile rewards, cloud computing)
2. search_keywords: 3-5 search terms that would find RELEVANT competitive intelligence (not the company's own code)
3. npm_packages: For "technology" type, list 6-8 relevant npm packages. For "company" or "market" type, list 3-4 packages the company/market is known to use or compete with. If unclear, return empty array.
4. competitors: List 3-6 known competitors or related companies in this space
5. industry: The industry this belongs to

Respond ONLY in JSON.`);

        const topicType = strategy.topic_type || 'technology';
        const searchKeywords = strategy.search_keywords || [topic];
        const competitors = strategy.competitors || [];

        // ────── STEP 2: Fetch npm data (adapted by topic type) ──────
        let npmData: NpmPackageData[] = [];
        const packages = (strategy.npm_packages || []).slice(0, 8);

        if (packages.length > 0) {
            onApiCall?.('npm Registry', `Fetching download stats for ${packages.length} packages: ${packages.join(', ')}`);
            npmData = await fetchNpmBulk(packages);
            apiCalls += packages.length;
        }

        // ────── STEP 3: Fetch HackerNews discussions (use best keywords) ──────
        const hnQuery = topicType === 'technology' ? topic : searchKeywords[0] || topic;
        onApiCall?.('HackerNews API', `Searching discussions about: ${hnQuery}`);
        const hnData = await searchHackerNews(hnQuery, 10);
        apiCalls++;

        // For companies/markets, also search with the company name directly
        let hnDataExtra: HackerNewsItem[] = [];
        if (topicType !== 'technology' && searchKeywords.length > 1) {
            const extraQuery = searchKeywords[1];
            onApiCall?.('HackerNews API', `Additional search: ${extraQuery}`);
            hnDataExtra = await searchHackerNews(extraQuery, 5);
            apiCalls++;
        }
        const allHnData = [...hnData, ...hnDataExtra];

        // ────── STEP 4: Fetch GitHub repos ──────
        let githubRepos: any[] = [];
        const ghQuery = topicType === 'technology' ? topic : searchKeywords.join(' ');
        onApiCall?.('GitHub API', `Searching repositories for: ${ghQuery}`);
        try {
            const ghHeaders: Record<string, string> = {
                'Accept': 'application/vnd.github.v3+json',
                'User-Agent': 'Agora-Orchestrator/0.1',
            };
            if (config.githubToken) ghHeaders['Authorization'] = `Bearer ${config.githubToken}`;

            const ghRes = await fetch(
                `https://api.github.com/search/repositories?q=${encodeURIComponent(ghQuery)}&sort=stars&per_page=10`,
                { headers: ghHeaders }
            );
            if (ghRes.ok) {
                const ghData = await ghRes.json() as any;
                githubRepos = (ghData.items || []).map((r: any) => ({
                    name: r.full_name,
                    stars: r.stargazers_count,
                    description: r.description,
                    language: r.language,
                    updatedAt: r.updated_at,
                }));
            }
            apiCalls++;
        } catch { /* optional data */ }

        // ────── STEP 5: Compile data with context ──────
        const dataSummary = JSON.stringify({
            topic,
            topic_type: topicType,
            industry: strategy.industry,
            known_competitors: competitors,
            npm_packages: npmData.map(p => ({
                name: p.name,
                version: p.version,
                monthlyDownloads: p.monthlyDownloads,
                dependencies: p.dependencies,
                maintainers: p.maintainers,
                lastPublish: p.lastPublished,
                license: p.license,
            })),
            hackernews_discussions: allHnData.slice(0, 10).map(h => ({
                title: h.title,
                points: h.points,
                comments: h.numComments,
                date: h.createdAt,
            })),
            github_repos: githubRepos.slice(0, 8),
        }, null, 2);

        // ────── STEP 6: Generate intelligence report ──────
        onApiCall?.('Gemini AI', 'Analyzing collected data and generating competitive intelligence report');
        apiCalls++;

        const analysisPrompt = topicType === 'technology'
            ? `Analyze this market data and produce a competitive intelligence report:\n\n${dataSummary}`
            : `Analyze this competitive intelligence data about the ${topicType} "${topic}" in the ${strategy.industry} industry.
Known competitors: ${competitors.join(', ')}

IMPORTANT: Focus your analysis on the COMPANY/PRODUCT "${topic}" and its competitive position. 
Do NOT confuse developer libraries (like node-fetch) with the actual company.
Use the HackerNews discussions and GitHub data as supplementary signals only.
If npm data is irrelevant to the company, acknowledge that and focus on what IS relevant.

Data collected:\n\n${dataSummary}`;

        const result = await this.call(analysisPrompt);

        return {
            report: result.content,
            npmData,
            hnData: allHnData,
            apiCalls,
            latencyMs: Date.now() - start,
        };
    }
}
