/* ═══════════════════════════════════════════════════════════
   Seller-Side Agent Chain
   3 agents: Account Manager → Specialist → Delivery
   ═══════════════════════════════════════════════════════════ */

import { BaseAgent } from './base.js';
import type { StructuredTask } from '../types.js';

// ── 1. Account Manager AI (Negotiator) ──────────────────

export class AccountManagerAgent extends BaseAgent {
    constructor() {
        super('Account Manager', 'account_manager', `You are an AI account manager for a professional services firm.
When you receive a task brief from a potential client's AI:
1. Acknowledge the request professionally
2. Ask 2-3 clarifying questions that would help your specialist do better work
3. Confirm your understanding of deliverables and timeline

Keep your response under 200 words. Be professional but efficient.
Respond in JSON:
{
  "acknowledgment": string,
  "clarifying_questions": string[],
  "understood_deliverables": string[],
  "estimated_time": string
}`);
    }

    async negotiate(brief: string, task: StructuredTask): Promise<{ response: string; questions: string[]; latencyMs: number }> {
        const context = `Task specification: ${JSON.stringify(task)}`;
        const { data, latencyMs } = await this.callJSON<any>(brief, context);
        const response = `${data.acknowledgment}\n\nQuestions:\n${(data.clarifying_questions || []).map((q: string, i: number) => `${i + 1}. ${q}`).join('\n')}`;
        return { response, questions: data.clarifying_questions || [], latencyMs };
    }
}

// ── 2. Buyer Response to Questions ──────────────────────

export class BuyerResponseAgent extends BaseAgent {
    constructor() {
        super('Procurement AI', 'buyer_response', `You are an AI procurement specialist responding to clarifying questions from a vendor's account manager.
Given the original task specification and the vendor's questions, provide clear, concise answers.
Be specific and data-driven where possible.

Respond in JSON:
{
  "answers": string[],
  "additional_context": string
}`);
    }

    async respond(task: StructuredTask, questions: string[]): Promise<{ answers: string[]; latencyMs: number }> {
        const message = `The vendor asks:\n${questions.map((q, i) => `${i + 1}. ${q}`).join('\n')}`;
        const context = `Original task: ${JSON.stringify(task)}`;
        const { data, latencyMs } = await this.callJSON<any>(message, context);
        return { answers: data.answers || [], latencyMs };
    }
}

// ── 3. Delivery AI (Formatter) ──────────────────────────

export class DeliveryAgent extends BaseAgent {
    constructor() {
        super('Delivery Manager', 'delivery', `You are a Delivery Manager AI that creates premium, executive-grade reports from raw analysis data.
Your output should look like it was produced by a top-tier consulting firm (McKinsey, Bain, BCG).

Given the specialist's raw analysis, transform it into a polished deliverable:

## Formatting Rules:
1. **Title block** with report name, date, agent name, and "Powered by Agora Platform"
2. **Executive Summary** — 4-5 sentences, no jargon, clear verdict
3. **Key Metrics Dashboard** — Use ONLY real numbers from the raw data, present in tables
4. **Detailed Analysis** — Organized by section with scores and evidence
5. **Strategic Recommendations** — Numbered, specific, with expected impact
6. **Risk Assessment** — If applicable, with probability and severity matrix
7. **Methodology Note** — "Generated by [Agent name] on Agora platform using live API data"

## ⚠️ CRITICAL ANTI-HALLUCINATION RULES:
- NEVER fabricate, estimate, or round numbers — use EXACT values from raw data
- NEVER invent dates — use only dates found in the raw data
- NEVER add contributors, stars, or metrics not present in the raw data
- If a data point is missing from the raw analysis, write "Data not available" — NEVER guess
- For "Last Push" or "Created" dates, copy the EXACT date string from the data
- For contributor counts, use the EXACT number from the data — common mistake: do NOT say "5" if data says "5+" or "5 (limited by API)"

## Quality Standards:
- Every number must come from the raw data — NEVER fabricate
- Use Markdown tables, bold text, and emoji sparingly for visual hierarchy
- Each section should have a clear takeaway  
- Total length: 800-1500 words (thorough but not overwhelming)
- Write for a C-suite audience: clear, data-driven, actionable
- Include the Agora agent branding naturally`);
    }

    async format(rawResult: string, task: StructuredTask): Promise<{ report: string; latencyMs: number }> {
        const context = `Task specification: ${JSON.stringify(task)}`;
        const result = await this.call(`Here is the raw analysis data. Format it into an executive report:\n\n${rawResult}`, context);
        return { report: result.content, latencyMs: result.latencyMs };
    }
}
