import { llmText } from '../utils/llm.js';
import { getWeekString } from '../utils/storage.js';
import type { AnalysisResult } from '../analyzer/analyzer.js';
import type { EnrichedData } from '../enricher/enricher.js';

export async function generateReport(analysis: AnalysisResult, enriched: EnrichedData): Promise<string> {
    console.log('📝 Generating report...');

    const weekStr = getWeekString();
    const topTrends = analysis.trends.slice(0, 10);
    const risingTrends = analysis.trends.filter(t => t.direction === 'rising').slice(0, 5);
    const decliningTrends = analysis.trends.filter(t => t.direction === 'declining').slice(0, 5);

    const prompt = `You are a senior market analyst for AGORA — a trusted marketplace for AI agents and MCP servers.

Generate a weekly trend report in Markdown based on the following data. Be specific, cite numbers, and provide actionable insights.

ANALYSIS DATA:
- Top trends: ${JSON.stringify(topTrends)}
- Rising trends: ${JSON.stringify(risingTrends)}
- Declining trends: ${JSON.stringify(decliningTrends)}
- White spaces: ${JSON.stringify(analysis.white_spaces)}
- Competitor insights: ${JSON.stringify(analysis.competitor_insights)}
- Ecosystem health: ${JSON.stringify(analysis.ecosystem_health)}
- NPM summary: ${JSON.stringify(enriched.npm_summary)}
- Top HN stories: ${JSON.stringify(enriched.stories.slice(0, 10).map(s => ({ title: s.title, score: s.score, topic: s.topic, sentiment: s.sentiment })))}

Write the report in this structure:

# 📊 Agora Trend Report — ${weekStr}

## Executive Summary
(3-4 sentences: key takeaway, biggest signal, most important action)

## 🔥 Top Trends This Week
(Top 5 trends with why they matter, numbers)

## 📈 Rising Stars
(Repos/packages growing fast — name, stars/downloads, why noteworthy)

## 📉 Declining
(What's losing traction and why)

## 🏢 Competitor Watch
(Status of each tracked competitor — activity, threat level)

## 💡 White Space Opportunities
(Niches with unmet demand — for Agora to target)

## 📦 NPM Ecosystem
(Download trends for key packages, what it means)

## 💬 Community Sentiment
(What HN/Reddit is saying, overall mood)

## 🎯 Actionable for Agora
(3-5 specific strategic actions based on this data)

## 📊 Key Metrics Dashboard
| Metric | Value |
|--------|-------|
| Total MCP repos tracked | ${analysis.ecosystem_health.total_mcp_repos} |
| Avg ecosystem relevance | ${analysis.ecosystem_health.avg_relevance}/10 |
| Community buzz index | ${analysis.ecosystem_health.buzz_index} |
| Sentiment: Positive | ${analysis.ecosystem_health.sentiment_breakdown.positive} |
| Sentiment: Neutral | ${analysis.ecosystem_health.sentiment_breakdown.neutral} |
| Sentiment: Negative | ${analysis.ecosystem_health.sentiment_breakdown.negative} |
| NPM total weekly downloads | ${enriched.npm_summary.total_weekly_downloads.toLocaleString()} |
| Fastest growing package | ${enriched.npm_summary.fastest_growing} |

---
*Generated by AGORA Trend Agent v0.1 • ${new Date().toISOString().split('T')[0]}*

Be data-driven. Cite specific numbers. No fluff. Write for a founder audience.`;

    const report = await llmText(prompt);
    console.log('  ✅ Report generated');
    return report;
}
